server:
  port: 8091
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://117.72.39.24:3306/bryant_music?characterEncoding=utf8&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: Xc@123456
    driverClassName: com.mysql.cj.jdbc.Driver

minio:
  point: http://8.134.64.89:9001
  username: bryant
  password: bryant0814
music-api-url:
  find: http://music.163.com/api/search/get/web?csrf_token=hlpretag=&hlposttag=&s=%s&type=1
  download: http://music.163.com/song/media/outer/url?id=%d